export const FETCH_PRODUCT_DEFINITIONS = 'FETCH_PRODUCT_DEFINITIONS';
export const RECEIVE_PRODUCT_DEFINITIONS = 'RECEIVE_PRODUCT_DEFINITIONS';
export const REMOVE_FROM_PRODUCT_DEFINITIONS = 'REMOVE_FROM_PRODUCT_DEFINITIONS';
export const REINSTATE_PRODUCT_DEFINITION = 'REINSTATE_PRODUCT_DEFINITION';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';